### PR TITLE
adeed "^" coloring

### PR DESCRIPTION
**Pull request by aayorishy**
John Doe says: look at that! ^laugh.

image

I don't know if GTAW:EU has it, but GTAWCN does. I haven't been on EU to check this.

### CODE REVIEW

**Comment by blancodagoat** [comment]
Owwww... that would be awesome, we don't have that sadly. 😢

**Comment by blancodagoat** [comment]
Awesome job though! I like that you're editing it for the other Chinese GTA World! ❤️

**Comment by aayorishy** [comment]
this's ur work, i just translated it so that GTAWCN can use it. ❤️❤️

**Comment by aayorishy** [comment]
I couldn't have done such a great job. You guys made GTAW what it is. ahahah

**Pull request closed without merging**
